### ISSUE TITLE
Error on delete/destroy

### ISSUE THREAD

**Issue by loeffel-io** [dangvanthanh/vue-ckeditor2#45] opened 2017-09-25 15:05 UTC
Hey, 
i get this error when i delete/destroy the ckeditor (remove it from the DOM):

`Uncaught TypeError: Cannot read property 'getRanges' of null`

I don't get this error message when i click inside the ckeditor (focus) before i delete the item. Can u please check this. 

Thanks 👍

**Comment by dangvanthanh** [comment] 2017-09-26 02:08
Hi what the method you use detele/destroy the ckeditor?

**Comment by renatosistemasvc** [comment] 2017-10-17 02:44
I also have this error. Any solution?

The error appears when I enter and exit the page that has the ckeditor.

**Comment by loeffel-io** [comment] 2017-10-17 15:36
Fixed in 1.11.0 👍

**Comment by renatosistemasvc** [comment] 2017-10-17 18:50
I'm using the 

"vue-ckeditor2" version: "^ 1.16.0"
vuejs: "vue": "^2.4.2"

and I get the error opening the ckeditor and exit. 
if before leaving I focus on ckeditor the error does not appear

my erro:

`Uncaught TypeError: Cannot read property 'getRanges' of null
`
Any solution?

**Comment by dangvanthanh** [comment] 2018-05-28 16:03
Duplicate of #49

**Comment by SidFeng** [comment] 2018-08-13 11:56
![image](https://user-images.githubusercontent.com/6702354/44030285-f328693c-9f32-11e8-8667-fb49a6190c2d.png)
same problem

**Comment by dangvanthanh** [comment] 2018-10-21 03:44
Hi @SidFeng 

I was fixed in `2.0.10`. Detail fix in #49

**Closed by dangvanthanh** 2018-10-21 03:44 UTC
Labels: BUG
